import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex ${pretendard.variable} flex flex-col items-center justify-center `}
      >
        <div className=" w-full justify-center">
          <div className="min-w-[320px] w-[calc(100%-40px)] ml-[20px] mr-[20px] ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
